import { applyD1Migrations, env, type D1Migration } from "cloudflare:test";

declare global {
  // Declaration merging into a global namespace has no ES module equivalent, so
  // namespace is required here
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace Cloudflare {
    // cloudflare:test's env type is Cloudflare.Env, generated by `wrangler
    // types`; this merges in the test-only bindings
    interface Env {
      TEST_MIGRATIONS: D1Migration[];
    }
  }
}

// Apply the migrations to each test worker's isolated D1 as it starts.
// The migration array is injected by vitest.config.mts through the
// TEST_MIGRATIONS binding.
await applyD1Migrations(env.DB, env.TEST_MIGRATIONS);
